id: AD43A6F1F
title: Complete text
type: translation
source_metadata:
  languages:
  - sa
  - bo
  datatype: PlainText
  created_at: 2022-03-02 08:59:49.942856
  last_modified_at: 2022-03-02 08:59:49.942867
